#=========================================================================
# ASIC Design Kit -- FreePDK45 + NanGate Open Cell Library
#=========================================================================
# Author : Christopher Torng
# Date   : June 7, 2019
#

name: freepdk-45nm

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs && cd outputs
  - ln -sf ../{adk_view} adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: freepdk-45nm
  adk_view: stdview

