# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pgen_interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pgen_interface.proto',
  package='',
  serialized_pb=_b('\n\x14pgen_interface.proto\"V\n\tPgenInput\x12\x0c\n\x04mode\x18\x01 \x02(\x05\x12\x13\n\x0btemperature\x18\x02 \x02(\x05\x12\x0c\n\x04node\x18\x03 \x02(\x05\x12\x0b\n\x03Vdd\x18\x04 \x01(\x01\x12\x0b\n\x03Vth\x18\x05 \x01(\x01\"\xa7\x05\n\nPgenOutput\x12)\n\nuser_input\x18\x01 \x02(\x0b\x32\x15.PgenOutput.UserInput\x12\x35\n\x10output_parameter\x18\x02 \x02(\x0b\x32\x1b.PgenOutput.OutputParameter\x1a\x62\n\tUserInput\x12\x13\n\x0btemperature\x18\x01 \x02(\x05\x12\x17\n\x0ftechnology_node\x18\x02 \x02(\x05\x12\x0c\n\x04mode\x18\x03 \x02(\x05\x12\x0b\n\x03Vdd\x18\x04 \x02(\x01\x12\x0c\n\x04Vth0\x18\x05 \x02(\x01\x1a\xd2\x03\n\x0fOutputParameter\x12\x30\n\x04nmos\x18\x01 \x02(\x0b\x32\".PgenOutput.OutputParameter.Mosfet\x12\x34\n\x08nmos_ref\x18\x02 \x02(\x0b\x32\".PgenOutput.OutputParameter.Mosfet\x12\x30\n\x04pmos\x18\x03 \x02(\x0b\x32\".PgenOutput.OutputParameter.Mosfet\x12\x34\n\x08pmos_ref\x18\x04 \x02(\x0b\x32\".PgenOutput.OutputParameter.Mosfet\x12.\n\x04wire\x18\x05 \x02(\x0b\x32 .PgenOutput.OutputParameter.Wire\x12\x32\n\x08wire_ref\x18\x06 \x02(\x0b\x32 .PgenOutput.OutputParameter.Wire\x1an\n\x06Mosfet\x12\x0b\n\x03Vdd\x18\x01 \x02(\x01\x12\x0c\n\x04Vth0\x18\x02 \x02(\x01\x12\x0e\n\x06Vth_on\x18\x03 \x02(\x01\x12\x0f\n\x07Vth_off\x18\x04 \x02(\x01\x12\x0b\n\x03Ion\x18\x05 \x02(\x01\x12\x0c\n\x04Isub\x18\x06 \x02(\x01\x12\r\n\x05Igate\x18\x07 \x02(\x01\x1a\x1b\n\x04Wire\x12\x13\n\x0bResistivity\x18\x01 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PGENINPUT = _descriptor.Descriptor(
  name='PgenInput',
  full_name='PgenInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='PgenInput.mode', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='PgenInput.temperature', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node', full_name='PgenInput.node', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vdd', full_name='PgenInput.Vdd', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vth', full_name='PgenInput.Vth', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=110,
)


_PGENOUTPUT_USERINPUT = _descriptor.Descriptor(
  name='UserInput',
  full_name='PgenOutput.UserInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='PgenOutput.UserInput.temperature', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='technology_node', full_name='PgenOutput.UserInput.technology_node', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='PgenOutput.UserInput.mode', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vdd', full_name='PgenOutput.UserInput.Vdd', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vth0', full_name='PgenOutput.UserInput.Vth0', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=323,
)

_PGENOUTPUT_OUTPUTPARAMETER_MOSFET = _descriptor.Descriptor(
  name='Mosfet',
  full_name='PgenOutput.OutputParameter.Mosfet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Vdd', full_name='PgenOutput.OutputParameter.Mosfet.Vdd', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vth0', full_name='PgenOutput.OutputParameter.Mosfet.Vth0', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vth_on', full_name='PgenOutput.OutputParameter.Mosfet.Vth_on', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vth_off', full_name='PgenOutput.OutputParameter.Mosfet.Vth_off', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ion', full_name='PgenOutput.OutputParameter.Mosfet.Ion', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Isub', full_name='PgenOutput.OutputParameter.Mosfet.Isub', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Igate', full_name='PgenOutput.OutputParameter.Mosfet.Igate', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=763,
)

_PGENOUTPUT_OUTPUTPARAMETER_WIRE = _descriptor.Descriptor(
  name='Wire',
  full_name='PgenOutput.OutputParameter.Wire',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Resistivity', full_name='PgenOutput.OutputParameter.Wire.Resistivity', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=792,
)

_PGENOUTPUT_OUTPUTPARAMETER = _descriptor.Descriptor(
  name='OutputParameter',
  full_name='PgenOutput.OutputParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nmos', full_name='PgenOutput.OutputParameter.nmos', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nmos_ref', full_name='PgenOutput.OutputParameter.nmos_ref', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pmos', full_name='PgenOutput.OutputParameter.pmos', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pmos_ref', full_name='PgenOutput.OutputParameter.pmos_ref', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wire', full_name='PgenOutput.OutputParameter.wire', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wire_ref', full_name='PgenOutput.OutputParameter.wire_ref', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PGENOUTPUT_OUTPUTPARAMETER_MOSFET, _PGENOUTPUT_OUTPUTPARAMETER_WIRE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=792,
)

_PGENOUTPUT = _descriptor.Descriptor(
  name='PgenOutput',
  full_name='PgenOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_input', full_name='PgenOutput.user_input', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_parameter', full_name='PgenOutput.output_parameter', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PGENOUTPUT_USERINPUT, _PGENOUTPUT_OUTPUTPARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=792,
)

_PGENOUTPUT_USERINPUT.containing_type = _PGENOUTPUT
_PGENOUTPUT_OUTPUTPARAMETER_MOSFET.containing_type = _PGENOUTPUT_OUTPUTPARAMETER
_PGENOUTPUT_OUTPUTPARAMETER_WIRE.containing_type = _PGENOUTPUT_OUTPUTPARAMETER
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['nmos'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_MOSFET
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['nmos_ref'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_MOSFET
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['pmos'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_MOSFET
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['pmos_ref'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_MOSFET
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['wire'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_WIRE
_PGENOUTPUT_OUTPUTPARAMETER.fields_by_name['wire_ref'].message_type = _PGENOUTPUT_OUTPUTPARAMETER_WIRE
_PGENOUTPUT_OUTPUTPARAMETER.containing_type = _PGENOUTPUT
_PGENOUTPUT.fields_by_name['user_input'].message_type = _PGENOUTPUT_USERINPUT
_PGENOUTPUT.fields_by_name['output_parameter'].message_type = _PGENOUTPUT_OUTPUTPARAMETER
DESCRIPTOR.message_types_by_name['PgenInput'] = _PGENINPUT
DESCRIPTOR.message_types_by_name['PgenOutput'] = _PGENOUTPUT

PgenInput = _reflection.GeneratedProtocolMessageType('PgenInput', (_message.Message,), dict(
  DESCRIPTOR = _PGENINPUT,
  __module__ = 'pgen_interface_pb2'
  # @@protoc_insertion_point(class_scope:PgenInput)
  ))
_sym_db.RegisterMessage(PgenInput)

PgenOutput = _reflection.GeneratedProtocolMessageType('PgenOutput', (_message.Message,), dict(

  UserInput = _reflection.GeneratedProtocolMessageType('UserInput', (_message.Message,), dict(
    DESCRIPTOR = _PGENOUTPUT_USERINPUT,
    __module__ = 'pgen_interface_pb2'
    # @@protoc_insertion_point(class_scope:PgenOutput.UserInput)
    ))
  ,

  OutputParameter = _reflection.GeneratedProtocolMessageType('OutputParameter', (_message.Message,), dict(

    Mosfet = _reflection.GeneratedProtocolMessageType('Mosfet', (_message.Message,), dict(
      DESCRIPTOR = _PGENOUTPUT_OUTPUTPARAMETER_MOSFET,
      __module__ = 'pgen_interface_pb2'
      # @@protoc_insertion_point(class_scope:PgenOutput.OutputParameter.Mosfet)
      ))
    ,

    Wire = _reflection.GeneratedProtocolMessageType('Wire', (_message.Message,), dict(
      DESCRIPTOR = _PGENOUTPUT_OUTPUTPARAMETER_WIRE,
      __module__ = 'pgen_interface_pb2'
      # @@protoc_insertion_point(class_scope:PgenOutput.OutputParameter.Wire)
      ))
    ,
    DESCRIPTOR = _PGENOUTPUT_OUTPUTPARAMETER,
    __module__ = 'pgen_interface_pb2'
    # @@protoc_insertion_point(class_scope:PgenOutput.OutputParameter)
    ))
  ,
  DESCRIPTOR = _PGENOUTPUT,
  __module__ = 'pgen_interface_pb2'
  # @@protoc_insertion_point(class_scope:PgenOutput)
  ))
_sym_db.RegisterMessage(PgenOutput)
_sym_db.RegisterMessage(PgenOutput.UserInput)
_sym_db.RegisterMessage(PgenOutput.OutputParameter)
_sym_db.RegisterMessage(PgenOutput.OutputParameter.Mosfet)
_sym_db.RegisterMessage(PgenOutput.OutputParameter.Wire)


# @@protoc_insertion_point(module_scope)
